POST http://localhost:8080/products
Content-Type: application/x-www-form-urlencoded

name=alpargatas&price=13

name=boots&price=44

name=shoes&price=23


###
GET http://localhost:8080/products
Accept: application/json

###
DELETE http://localhost:8080/products/{name}
Content-Type: application/x-www-form-urlencoded

products.remove(product)